name: screen_tap_blocker
description: A Flutter plugin to block all screen taps temporarily on Android and iOS.
version: 0.1.0
homepage: https://github.com/aibekdv/screen_tap_blocker
repository: https://github.com/aibekdv/screen_tap_blocker

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.screen_tap_blocker
        pluginClass: ScreenTapBlockerPlugin
      ios:
        pluginClass: ScreenTapBlockerPlugin
